import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], variable: '--font-poppins', weight: '400' })

export const metadata = {
  title: 'Remates Sanchez - Online',
  description: 'Generated by create next app',  
  icon: '/favicon.ico',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>      
      <body className={inter.className}>

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
